/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.gameparams.jooq.db.tables.records;


import com.bsu.ugame.gameparams.jooq.db.tables.TControl;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TControlRecord extends UpdatableRecordImpl<TControlRecord> implements Record8<UInteger, String, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = 1124075609;

    /**
     * Setter for <code>gameparams.t_control.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>gameparams.t_control.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>gameparams.t_control.gameappid</code>. 游戏的appid
     */
    public void setGameappid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gameparams.t_control.gameappid</code>. 游戏的appid
     */
    public String getGameappid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gameparams.t_control.name</code>. 参数名，参数的功能名
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gameparams.t_control.name</code>. 参数名，参数的功能名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gameparams.t_control.key</code>. 英文的参数名
     */
    public void setKey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gameparams.t_control.key</code>. 英文的参数名
     */
    public String getKey() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gameparams.t_control.memo</code>. 参数的注释
     */
    public void setMemo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gameparams.t_control.memo</code>. 参数的注释
     */
    public String getMemo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gameparams.t_control.default</code>. 参数的默认值
     */
    public void setDefault(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gameparams.t_control.default</code>. 参数的默认值
     */
    public String getDefault() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gameparams.t_control.type</code>. 参数类型(一般不会使用)
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gameparams.t_control.type</code>. 参数类型(一般不会使用)
     */
    public String getType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>gameparams.t_control.length</code>. 参数长度(一般不会使用)
     */
    public void setLength(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>gameparams.t_control.length</code>. 参数长度(一般不会使用)
     */
    public Integer getLength() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UInteger, String, String, String, String, String, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UInteger, String, String, String, String, String, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TControl.T_CONTROL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TControl.T_CONTROL.GAMEAPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TControl.T_CONTROL.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TControl.T_CONTROL.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TControl.T_CONTROL.MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TControl.T_CONTROL.DEFAULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TControl.T_CONTROL.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TControl.T_CONTROL.LENGTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGameappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDefault();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getLength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGameappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDefault();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getLength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TControlRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TControlRecord value2(String value) {
        setGameappid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TControlRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TControlRecord value4(String value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TControlRecord value5(String value) {
        setMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TControlRecord value6(String value) {
        setDefault(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TControlRecord value7(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TControlRecord value8(Integer value) {
        setLength(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TControlRecord values(UInteger value1, String value2, String value3, String value4, String value5, String value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TControlRecord
     */
    public TControlRecord() {
        super(TControl.T_CONTROL);
    }

    /**
     * Create a detached, initialised TControlRecord
     */
    public TControlRecord(UInteger id, String gameappid, String name, String key, String memo, String default_, String type, Integer length) {
        super(TControl.T_CONTROL);

        set(0, id);
        set(1, gameappid);
        set(2, name);
        set(3, key);
        set(4, memo);
        set(5, default_);
        set(6, type);
        set(7, length);
    }
}
