/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.gameparams.jooq.db.tables.records;


import com.bsu.ugame.gameparams.jooq.db.tables.TJumpdata;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TJumpdataRecord extends UpdatableRecordImpl<TJumpdataRecord> implements Record5<UInteger, String, String, Integer, Timestamp> {

    private static final long serialVersionUID = 146191337;

    /**
     * Setter for <code>gameparams.t_jumpdata.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>gameparams.t_jumpdata.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>gameparams.t_jumpdata.gameappid</code>.
     */
    public void setGameappid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gameparams.t_jumpdata.gameappid</code>.
     */
    public String getGameappid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gameparams.t_jumpdata.objectappid</code>.
     */
    public void setObjectappid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gameparams.t_jumpdata.objectappid</code>.
     */
    public String getObjectappid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gameparams.t_jumpdata.usercount</code>.
     */
    public void setUsercount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gameparams.t_jumpdata.usercount</code>.
     */
    public Integer getUsercount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>gameparams.t_jumpdata.createtime</code>.
     */
    public void setCreatetime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>gameparams.t_jumpdata.createtime</code>.
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, String, String, Integer, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, String, String, Integer, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TJumpdata.T_JUMPDATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TJumpdata.T_JUMPDATA.GAMEAPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TJumpdata.T_JUMPDATA.OBJECTAPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TJumpdata.T_JUMPDATA.USERCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TJumpdata.T_JUMPDATA.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGameappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getObjectappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getUsercount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGameappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getObjectappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getUsercount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TJumpdataRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TJumpdataRecord value2(String value) {
        setGameappid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TJumpdataRecord value3(String value) {
        setObjectappid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TJumpdataRecord value4(Integer value) {
        setUsercount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TJumpdataRecord value5(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TJumpdataRecord values(UInteger value1, String value2, String value3, Integer value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TJumpdataRecord
     */
    public TJumpdataRecord() {
        super(TJumpdata.T_JUMPDATA);
    }

    /**
     * Create a detached, initialised TJumpdataRecord
     */
    public TJumpdataRecord(UInteger id, String gameappid, String objectappid, Integer usercount, Timestamp createtime) {
        super(TJumpdata.T_JUMPDATA);

        set(0, id);
        set(1, gameappid);
        set(2, objectappid);
        set(3, usercount);
        set(4, createtime);
    }
}
