/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.gameparams.jooq.db.tables.records;


import com.bsu.ugame.gameparams.jooq.db.tables.TMoregames;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMoregamesRecord extends UpdatableRecordImpl<TMoregamesRecord> implements Record7<UInteger, String, String, String, String, Integer, String> {

    private static final long serialVersionUID = 1664642723;

    /**
     * Setter for <code>gameparams.t_moregames.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>gameparams.t_moregames.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>gameparams.t_moregames.gameappid</code>. 游戏ID
     */
    public void setGameappid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gameparams.t_moregames.gameappid</code>. 游戏ID
     */
    public String getGameappid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gameparams.t_moregames.iconurl</code>.
     */
    public void setIconurl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gameparams.t_moregames.iconurl</code>.
     */
    public String getIconurl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gameparams.t_moregames.title</code>. 游戏标题
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gameparams.t_moregames.title</code>. 游戏标题
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gameparams.t_moregames.jumpappid</code>. 跳转的appid
     */
    public void setJumpappid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gameparams.t_moregames.jumpappid</code>. 跳转的appid
     */
    public String getJumpappid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gameparams.t_moregames.position</code>. 跳转所在位置
     */
    public void setPosition(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>gameparams.t_moregames.position</code>. 跳转所在位置
     */
    public Integer getPosition() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>gameparams.t_moregames.path</code>. 跳转的路径
     */
    public void setPath(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>gameparams.t_moregames.path</code>. 跳转的路径
     */
    public String getPath() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, String, String, String, String, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, String, String, String, String, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TMoregames.T_MOREGAMES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TMoregames.T_MOREGAMES.GAMEAPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TMoregames.T_MOREGAMES.ICONURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TMoregames.T_MOREGAMES.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TMoregames.T_MOREGAMES.JUMPAPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TMoregames.T_MOREGAMES.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TMoregames.T_MOREGAMES.PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGameappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getIconurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getJumpappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGameappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIconurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getJumpappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMoregamesRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMoregamesRecord value2(String value) {
        setGameappid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMoregamesRecord value3(String value) {
        setIconurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMoregamesRecord value4(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMoregamesRecord value5(String value) {
        setJumpappid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMoregamesRecord value6(Integer value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMoregamesRecord value7(String value) {
        setPath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMoregamesRecord values(UInteger value1, String value2, String value3, String value4, String value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TMoregamesRecord
     */
    public TMoregamesRecord() {
        super(TMoregames.T_MOREGAMES);
    }

    /**
     * Create a detached, initialised TMoregamesRecord
     */
    public TMoregamesRecord(UInteger id, String gameappid, String iconurl, String title, String jumpappid, Integer position, String path) {
        super(TMoregames.T_MOREGAMES);

        set(0, id);
        set(1, gameappid);
        set(2, iconurl);
        set(3, title);
        set(4, jumpappid);
        set(5, position);
        set(6, path);
    }
}
