/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.gameparams.jooq.db.tables.records;


import com.bsu.ugame.gameparams.jooq.db.tables.TMorejump;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMorejumpRecord extends UpdatableRecordImpl<TMorejumpRecord> implements Record5<UInteger, String, String, String, Timestamp> {

    private static final long serialVersionUID = 1089368758;

    /**
     * Setter for <code>gameparams.t_morejump.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>gameparams.t_morejump.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>gameparams.t_morejump.gameappid</code>. 游戏appid
     */
    public void setGameappid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gameparams.t_morejump.gameappid</code>. 游戏appid
     */
    public String getGameappid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gameparams.t_morejump.objectappid</code>. 目标appid，跳到了哪个app
     */
    public void setObjectappid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gameparams.t_morejump.objectappid</code>. 目标appid，跳到了哪个app
     */
    public String getObjectappid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gameparams.t_morejump.userid</code>. 跳转的用户数量
     */
    public void setUserid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gameparams.t_morejump.userid</code>. 跳转的用户数量
     */
    public String getUserid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gameparams.t_morejump.createtime</code>.
     */
    public void setCreatetime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>gameparams.t_morejump.createtime</code>.
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, String, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, String, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TMorejump.T_MOREJUMP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TMorejump.T_MOREJUMP.GAMEAPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TMorejump.T_MOREJUMP.OBJECTAPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TMorejump.T_MOREJUMP.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TMorejump.T_MOREJUMP.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGameappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getObjectappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGameappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getObjectappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMorejumpRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMorejumpRecord value2(String value) {
        setGameappid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMorejumpRecord value3(String value) {
        setObjectappid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMorejumpRecord value4(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMorejumpRecord value5(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMorejumpRecord values(UInteger value1, String value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TMorejumpRecord
     */
    public TMorejumpRecord() {
        super(TMorejump.T_MOREJUMP);
    }

    /**
     * Create a detached, initialised TMorejumpRecord
     */
    public TMorejumpRecord(UInteger id, String gameappid, String objectappid, String userid, Timestamp createtime) {
        super(TMorejump.T_MOREJUMP);

        set(0, id);
        set(1, gameappid);
        set(2, objectappid);
        set(3, userid);
        set(4, createtime);
    }
}
