/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.gameparams.jooq.db.tables.records;


import com.bsu.ugame.gameparams.jooq.db.tables.TPlayer;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPlayerRecord extends UpdatableRecordImpl<TPlayerRecord> implements Record18<UInteger, String, String, String, Integer, String, Timestamp, Timestamp, Boolean, UInteger, Integer, UInteger, UInteger, Integer, String, String, String, String> {

    private static final long serialVersionUID = 1101531114;

    /**
     * Setter for <code>gameparams.t_player.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>gameparams.t_player.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>gameparams.t_player.gameappid</code>. 游戏appid
     */
    public void setGameappid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gameparams.t_player.gameappid</code>. 游戏appid
     */
    public String getGameappid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gameparams.t_player.nickname</code>. 昵称
     */
    public void setNickname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gameparams.t_player.nickname</code>. 昵称
     */
    public String getNickname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gameparams.t_player.avatarurl</code>. 头像url
     */
    public void setAvatarurl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gameparams.t_player.avatarurl</code>. 头像url
     */
    public String getAvatarurl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gameparams.t_player.gender</code>. 性别
     */
    public void setGender(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>gameparams.t_player.gender</code>. 性别
     */
    public Integer getGender() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>gameparams.t_player.openid</code>.
     */
    public void setOpenid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gameparams.t_player.openid</code>.
     */
    public String getOpenid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gameparams.t_player.createtime</code>. 创建时间
     */
    public void setCreatetime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>gameparams.t_player.createtime</code>. 创建时间
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>gameparams.t_player.lastlogintime</code>. 最后登录时间
     */
    public void setLastlogintime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>gameparams.t_player.lastlogintime</code>. 最后登录时间
     */
    public Timestamp getLastlogintime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>gameparams.t_player.signin</code>. 是否签到
     */
    public void setSignin(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>gameparams.t_player.signin</code>. 是否签到
     */
    public Boolean getSignin() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>gameparams.t_player.invite</code>. 邀请新用户数量
     */
    public void setInvite(UInteger value) {
        set(9, value);
    }

    /**
     * Getter for <code>gameparams.t_player.invite</code>. 邀请新用户数量
     */
    public UInteger getInvite() {
        return (UInteger) get(9);
    }

    /**
     * Setter for <code>gameparams.t_player.videocount</code>. 访问视频次数，上限为10，需要每天清0
     */
    public void setVideocount(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>gameparams.t_player.videocount</code>. 访问视频次数，上限为10，需要每天清0
     */
    public Integer getVideocount() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>gameparams.t_player.gold</code>. 用户金币数
     */
    public void setGold(UInteger value) {
        set(11, value);
    }

    /**
     * Getter for <code>gameparams.t_player.gold</code>. 用户金币数
     */
    public UInteger getGold() {
        return (UInteger) get(11);
    }

    /**
     * Setter for <code>gameparams.t_player.diamond</code>. 钻石数
     */
    public void setDiamond(UInteger value) {
        set(12, value);
    }

    /**
     * Getter for <code>gameparams.t_player.diamond</code>. 钻石数
     */
    public UInteger getDiamond() {
        return (UInteger) get(12);
    }

    /**
     * Setter for <code>gameparams.t_player.rankingsscore</code>. 排名分数
     */
    public void setRankingsscore(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>gameparams.t_player.rankingsscore</code>. 排名分数
     */
    public Integer getRankingsscore() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>gameparams.t_player.province</code>. 省份
     */
    public void setProvince(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>gameparams.t_player.province</code>. 省份
     */
    public String getProvince() {
        return (String) get(14);
    }

    /**
     * Setter for <code>gameparams.t_player.city</code>. 城市
     */
    public void setCity(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>gameparams.t_player.city</code>. 城市
     */
    public String getCity() {
        return (String) get(15);
    }

    /**
     * Setter for <code>gameparams.t_player.boxappid</code>. 用户来源渠道appid
     */
    public void setBoxappid(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>gameparams.t_player.boxappid</code>. 用户来源渠道appid
     */
    public String getBoxappid() {
        return (String) get(16);
    }

    /**
     * Setter for <code>gameparams.t_player.currentboxappid</code>. 用户当前的渠道app的id
     */
    public void setCurrentboxappid(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>gameparams.t_player.currentboxappid</code>. 用户当前的渠道app的id
     */
    public String getCurrentboxappid() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<UInteger, String, String, String, Integer, String, Timestamp, Timestamp, Boolean, UInteger, Integer, UInteger, UInteger, Integer, String, String, String, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<UInteger, String, String, String, Integer, String, Timestamp, Timestamp, Boolean, UInteger, Integer, UInteger, UInteger, Integer, String, String, String, String> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TPlayer.T_PLAYER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TPlayer.T_PLAYER.GAMEAPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TPlayer.T_PLAYER.NICKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TPlayer.T_PLAYER.AVATARURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TPlayer.T_PLAYER.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TPlayer.T_PLAYER.OPENID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TPlayer.T_PLAYER.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return TPlayer.T_PLAYER.LASTLOGINTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return TPlayer.T_PLAYER.SIGNIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field10() {
        return TPlayer.T_PLAYER.INVITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return TPlayer.T_PLAYER.VIDEOCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field12() {
        return TPlayer.T_PLAYER.GOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field13() {
        return TPlayer.T_PLAYER.DIAMOND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return TPlayer.T_PLAYER.RANKINGSSCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return TPlayer.T_PLAYER.PROVINCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return TPlayer.T_PLAYER.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return TPlayer.T_PLAYER.BOXAPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return TPlayer.T_PLAYER.CURRENTBOXAPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGameappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAvatarurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getLastlogintime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getSignin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component10() {
        return getInvite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getVideocount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component12() {
        return getGold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component13() {
        return getDiamond();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getRankingsscore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getBoxappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component18() {
        return getCurrentboxappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGameappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAvatarurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getLastlogintime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getSignin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value10() {
        return getInvite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getVideocount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value12() {
        return getGold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value13() {
        return getDiamond();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getRankingsscore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getBoxappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getCurrentboxappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value2(String value) {
        setGameappid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value3(String value) {
        setNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value4(String value) {
        setAvatarurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value5(Integer value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value6(String value) {
        setOpenid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value7(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value8(Timestamp value) {
        setLastlogintime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value9(Boolean value) {
        setSignin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value10(UInteger value) {
        setInvite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value11(Integer value) {
        setVideocount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value12(UInteger value) {
        setGold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value13(UInteger value) {
        setDiamond(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value14(Integer value) {
        setRankingsscore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value15(String value) {
        setProvince(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value16(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value17(String value) {
        setBoxappid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord value18(String value) {
        setCurrentboxappid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayerRecord values(UInteger value1, String value2, String value3, String value4, Integer value5, String value6, Timestamp value7, Timestamp value8, Boolean value9, UInteger value10, Integer value11, UInteger value12, UInteger value13, Integer value14, String value15, String value16, String value17, String value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TPlayerRecord
     */
    public TPlayerRecord() {
        super(TPlayer.T_PLAYER);
    }

    /**
     * Create a detached, initialised TPlayerRecord
     */
    public TPlayerRecord(UInteger id, String gameappid, String nickname, String avatarurl, Integer gender, String openid, Timestamp createtime, Timestamp lastlogintime, Boolean signin, UInteger invite, Integer videocount, UInteger gold, UInteger diamond, Integer rankingsscore, String province, String city, String boxappid, String currentboxappid) {
        super(TPlayer.T_PLAYER);

        set(0, id);
        set(1, gameappid);
        set(2, nickname);
        set(3, avatarurl);
        set(4, gender);
        set(5, openid);
        set(6, createtime);
        set(7, lastlogintime);
        set(8, signin);
        set(9, invite);
        set(10, videocount);
        set(11, gold);
        set(12, diamond);
        set(13, rankingsscore);
        set(14, province);
        set(15, city);
        set(16, boxappid);
        set(17, currentboxappid);
    }
}
