/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.gameparams.jooq.db.tables.records;


import com.bsu.ugame.gameparams.jooq.db.tables.TUser;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserRecord extends UpdatableRecordImpl<TUserRecord> implements Record9<UInteger, String, String, String, Boolean, Timestamp, Timestamp, String, String> {

    private static final long serialVersionUID = 757339228;

    /**
     * Setter for <code>gameparams.t_user.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>gameparams.t_user.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>gameparams.t_user.name</code>. 用户名
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gameparams.t_user.name</code>. 用户名
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gameparams.t_user.pwd</code>. 用户密码
     */
    public void setPwd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gameparams.t_user.pwd</code>. 用户密码
     */
    public String getPwd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gameparams.t_user.pwd_salt</code>.
     */
    public void setPwdSalt(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gameparams.t_user.pwd_salt</code>.
     */
    public String getPwdSalt() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gameparams.t_user.disable</code>. 用户是否启用，默认启用
     */
    public void setDisable(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>gameparams.t_user.disable</code>. 用户是否启用，默认启用
     */
    public Boolean getDisable() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>gameparams.t_user.regist_time</code>. 注册时间
     */
    public void setRegistTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>gameparams.t_user.regist_time</code>. 注册时间
     */
    public Timestamp getRegistTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>gameparams.t_user.last_login_time</code>. 最后登录时间
     */
    public void setLastLoginTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>gameparams.t_user.last_login_time</code>. 最后登录时间
     */
    public Timestamp getLastLoginTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>gameparams.t_user.last_login_ip</code>. 最后登录IP
     */
    public void setLastLoginIp(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>gameparams.t_user.last_login_ip</code>. 最后登录IP
     */
    public String getLastLoginIp() {
        return (String) get(7);
    }

    /**
     * Setter for <code>gameparams.t_user.auth</code>. 渠道权限 1:管理员 2:运营商 3:开发商
     */
    public void setAuth(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>gameparams.t_user.auth</code>. 渠道权限 1:管理员 2:运营商 3:开发商
     */
    public String getAuth() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UInteger, String, String, String, Boolean, Timestamp, Timestamp, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UInteger, String, String, String, Boolean, Timestamp, Timestamp, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TUser.T_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TUser.T_USER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TUser.T_USER.PWD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TUser.T_USER.PWD_SALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return TUser.T_USER.DISABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return TUser.T_USER.REGIST_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return TUser.T_USER.LAST_LOGIN_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TUser.T_USER.LAST_LOGIN_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TUser.T_USER.AUTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPwd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPwdSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getDisable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getRegistTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getLastLoginTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getLastLoginIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getAuth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPwd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPwdSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getDisable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getRegistTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getLastLoginTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLastLoginIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAuth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value3(String value) {
        setPwd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value4(String value) {
        setPwdSalt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value5(Boolean value) {
        setDisable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value6(Timestamp value) {
        setRegistTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value7(Timestamp value) {
        setLastLoginTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value8(String value) {
        setLastLoginIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord value9(String value) {
        setAuth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserRecord values(UInteger value1, String value2, String value3, String value4, Boolean value5, Timestamp value6, Timestamp value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUserRecord
     */
    public TUserRecord() {
        super(TUser.T_USER);
    }

    /**
     * Create a detached, initialised TUserRecord
     */
    public TUserRecord(UInteger id, String name, String pwd, String pwdSalt, Boolean disable, Timestamp registTime, Timestamp lastLoginTime, String lastLoginIp, String auth) {
        super(TUser.T_USER);

        set(0, id);
        set(1, name);
        set(2, pwd);
        set(3, pwdSalt);
        set(4, disable);
        set(5, registTime);
        set(6, lastLoginTime);
        set(7, lastLoginIp);
        set(8, auth);
    }
}
