/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.gameparams.jooq.db.tables;


import com.bsu.ugame.gameparams.jooq.db.Gameparams;
import com.bsu.ugame.gameparams.jooq.db.Indexes;
import com.bsu.ugame.gameparams.jooq.db.Keys;
import com.bsu.ugame.gameparams.jooq.db.tables.records.RUserGameRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RUserGame extends TableImpl<RUserGameRecord> {

    private static final long serialVersionUID = -1076603223;

    /**
     * The reference instance of <code>gameparams.r_user_game</code>
     */
    public static final RUserGame R_USER_GAME = new RUserGame();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RUserGameRecord> getRecordType() {
        return RUserGameRecord.class;
    }

    /**
     * The column <code>gameparams.r_user_game.id</code>.
     */
    public final TableField<RUserGameRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>gameparams.r_user_game.userid</code>.
     */
    public final TableField<RUserGameRecord, UInteger> USERID = createField("userid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>gameparams.r_user_game.gameid</code>.
     */
    public final TableField<RUserGameRecord, UInteger> GAMEID = createField("gameid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>gameparams.r_user_game</code> table reference
     */
    public RUserGame() {
        this(DSL.name("r_user_game"), null);
    }

    /**
     * Create an aliased <code>gameparams.r_user_game</code> table reference
     */
    public RUserGame(String alias) {
        this(DSL.name(alias), R_USER_GAME);
    }

    /**
     * Create an aliased <code>gameparams.r_user_game</code> table reference
     */
    public RUserGame(Name alias) {
        this(alias, R_USER_GAME);
    }

    private RUserGame(Name alias, Table<RUserGameRecord> aliased) {
        this(alias, aliased, null);
    }

    private RUserGame(Name alias, Table<RUserGameRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gameparams.GAMEPARAMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.R_USER_GAME_PRIMARY, Indexes.R_USER_GAME_UNI_USERID_GAMEAPPID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RUserGameRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_R_USER_GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RUserGameRecord> getPrimaryKey() {
        return Keys.KEY_R_USER_GAME_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RUserGameRecord>> getKeys() {
        return Arrays.<UniqueKey<RUserGameRecord>>asList(Keys.KEY_R_USER_GAME_PRIMARY, Keys.KEY_R_USER_GAME_UNI_USERID_GAMEAPPID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserGame as(String alias) {
        return new RUserGame(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RUserGame as(Name alias) {
        return new RUserGame(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RUserGame rename(String name) {
        return new RUserGame(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RUserGame rename(Name name) {
        return new RUserGame(name, null);
    }
}
