/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.gameparams.jooq.db.tables;


import com.bsu.ugame.gameparams.jooq.db.Gameparams;
import com.bsu.ugame.gameparams.jooq.db.Indexes;
import com.bsu.ugame.gameparams.jooq.db.Keys;
import com.bsu.ugame.gameparams.jooq.db.tables.records.TControlvalueRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TControlvalue extends TableImpl<TControlvalueRecord> {

    private static final long serialVersionUID = 212870127;

    /**
     * The reference instance of <code>gameparams.t_controlvalue</code>
     */
    public static final TControlvalue T_CONTROLVALUE = new TControlvalue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TControlvalueRecord> getRecordType() {
        return TControlvalueRecord.class;
    }

    /**
     * The column <code>gameparams.t_controlvalue.id</code>.
     */
    public final TableField<TControlvalueRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>gameparams.t_controlvalue.gameappid</code>. 游戏的appid
     */
    public final TableField<TControlvalueRecord, String> GAMEAPPID = createField("gameappid", org.jooq.impl.SQLDataType.VARCHAR(50), this, "游戏的appid");

    /**
     * The column <code>gameparams.t_controlvalue.version</code>. 该条参数数据对应的版本号
     */
    public final TableField<TControlvalueRecord, String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR(10), this, "该条参数数据对应的版本号");

    /**
     * The column <code>gameparams.t_controlvalue.value</code>. 每个gameappid对应的值
     */
    public final TableField<TControlvalueRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR(1000), this, "每个gameappid对应的值");

    /**
     * Create a <code>gameparams.t_controlvalue</code> table reference
     */
    public TControlvalue() {
        this(DSL.name("t_controlvalue"), null);
    }

    /**
     * Create an aliased <code>gameparams.t_controlvalue</code> table reference
     */
    public TControlvalue(String alias) {
        this(DSL.name(alias), T_CONTROLVALUE);
    }

    /**
     * Create an aliased <code>gameparams.t_controlvalue</code> table reference
     */
    public TControlvalue(Name alias) {
        this(alias, T_CONTROLVALUE);
    }

    private TControlvalue(Name alias, Table<TControlvalueRecord> aliased) {
        this(alias, aliased, null);
    }

    private TControlvalue(Name alias, Table<TControlvalueRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gameparams.GAMEPARAMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_CONTROLVALUE_PRIMARY, Indexes.T_CONTROLVALUE_UNI_GAMEAPPID_VERSION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TControlvalueRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_T_CONTROLVALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TControlvalueRecord> getPrimaryKey() {
        return Keys.KEY_T_CONTROLVALUE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TControlvalueRecord>> getKeys() {
        return Arrays.<UniqueKey<TControlvalueRecord>>asList(Keys.KEY_T_CONTROLVALUE_PRIMARY, Keys.KEY_T_CONTROLVALUE_UNI_GAMEAPPID_VERSION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TControlvalue as(String alias) {
        return new TControlvalue(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TControlvalue as(Name alias) {
        return new TControlvalue(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TControlvalue rename(String name) {
        return new TControlvalue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TControlvalue rename(Name name) {
        return new TControlvalue(name, null);
    }
}
