/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.gameparams.jooq.db.tables;


import com.bsu.ugame.gameparams.jooq.db.Gameparams;
import com.bsu.ugame.gameparams.jooq.db.Indexes;
import com.bsu.ugame.gameparams.jooq.db.Keys;
import com.bsu.ugame.gameparams.jooq.db.tables.records.TMoregamesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TMoregames extends TableImpl<TMoregamesRecord> {

    private static final long serialVersionUID = -1863119154;

    /**
     * The reference instance of <code>gameparams.t_moregames</code>
     */
    public static final TMoregames T_MOREGAMES = new TMoregames();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TMoregamesRecord> getRecordType() {
        return TMoregamesRecord.class;
    }

    /**
     * The column <code>gameparams.t_moregames.id</code>.
     */
    public final TableField<TMoregamesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>gameparams.t_moregames.gameappid</code>. 游戏ID
     */
    public final TableField<TMoregamesRecord, String> GAMEAPPID = createField("gameappid", org.jooq.impl.SQLDataType.VARCHAR(50), this, "游戏ID");

    /**
     * The column <code>gameparams.t_moregames.iconurl</code>.
     */
    public final TableField<TMoregamesRecord, String> ICONURL = createField("iconurl", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>gameparams.t_moregames.title</code>. 游戏标题
     */
    public final TableField<TMoregamesRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR(100), this, "游戏标题");

    /**
     * The column <code>gameparams.t_moregames.jumpappid</code>. 跳转的appid
     */
    public final TableField<TMoregamesRecord, String> JUMPAPPID = createField("jumpappid", org.jooq.impl.SQLDataType.VARCHAR(50), this, "跳转的appid");

    /**
     * The column <code>gameparams.t_moregames.position</code>. 跳转所在位置
     */
    public final TableField<TMoregamesRecord, Integer> POSITION = createField("position", org.jooq.impl.SQLDataType.INTEGER, this, "跳转所在位置");

    /**
     * The column <code>gameparams.t_moregames.path</code>. 跳转的路径
     */
    public final TableField<TMoregamesRecord, String> PATH = createField("path", org.jooq.impl.SQLDataType.VARCHAR(300), this, "跳转的路径");

    /**
     * Create a <code>gameparams.t_moregames</code> table reference
     */
    public TMoregames() {
        this(DSL.name("t_moregames"), null);
    }

    /**
     * Create an aliased <code>gameparams.t_moregames</code> table reference
     */
    public TMoregames(String alias) {
        this(DSL.name(alias), T_MOREGAMES);
    }

    /**
     * Create an aliased <code>gameparams.t_moregames</code> table reference
     */
    public TMoregames(Name alias) {
        this(alias, T_MOREGAMES);
    }

    private TMoregames(Name alias, Table<TMoregamesRecord> aliased) {
        this(alias, aliased, null);
    }

    private TMoregames(Name alias, Table<TMoregamesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gameparams.GAMEPARAMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_MOREGAMES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TMoregamesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_T_MOREGAMES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TMoregamesRecord> getPrimaryKey() {
        return Keys.KEY_T_MOREGAMES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TMoregamesRecord>> getKeys() {
        return Arrays.<UniqueKey<TMoregamesRecord>>asList(Keys.KEY_T_MOREGAMES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMoregames as(String alias) {
        return new TMoregames(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TMoregames as(Name alias) {
        return new TMoregames(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TMoregames rename(String name) {
        return new TMoregames(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TMoregames rename(Name name) {
        return new TMoregames(name, null);
    }
}
