/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.gameparams.jooq.db.tables;


import com.bsu.ugame.gameparams.jooq.db.Gameparams;
import com.bsu.ugame.gameparams.jooq.db.Indexes;
import com.bsu.ugame.gameparams.jooq.db.Keys;
import com.bsu.ugame.gameparams.jooq.db.tables.records.TUserrolesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserroles extends TableImpl<TUserrolesRecord> {

    private static final long serialVersionUID = -989010692;

    /**
     * The reference instance of <code>gameparams.t_userroles</code>
     */
    public static final TUserroles T_USERROLES = new TUserroles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUserrolesRecord> getRecordType() {
        return TUserrolesRecord.class;
    }

    /**
     * The column <code>gameparams.t_userroles.id</code>.
     */
    public final TableField<TUserrolesRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>gameparams.t_userroles.username</code>.
     */
    public final TableField<TUserrolesRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>gameparams.t_userroles.role_name</code>.
     */
    public final TableField<TUserrolesRecord, String> ROLE_NAME = createField("role_name", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>gameparams.t_userroles</code> table reference
     */
    public TUserroles() {
        this(DSL.name("t_userroles"), null);
    }

    /**
     * Create an aliased <code>gameparams.t_userroles</code> table reference
     */
    public TUserroles(String alias) {
        this(DSL.name(alias), T_USERROLES);
    }

    /**
     * Create an aliased <code>gameparams.t_userroles</code> table reference
     */
    public TUserroles(Name alias) {
        this(alias, T_USERROLES);
    }

    private TUserroles(Name alias, Table<TUserrolesRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserroles(Name alias, Table<TUserrolesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gameparams.GAMEPARAMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_USERROLES_IDX_USER_ROLES, Indexes.T_USERROLES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TUserrolesRecord, Long> getIdentity() {
        return Keys.IDENTITY_T_USERROLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TUserrolesRecord> getPrimaryKey() {
        return Keys.KEY_T_USERROLES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TUserrolesRecord>> getKeys() {
        return Arrays.<UniqueKey<TUserrolesRecord>>asList(Keys.KEY_T_USERROLES_PRIMARY, Keys.KEY_T_USERROLES_IDX_USER_ROLES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserroles as(String alias) {
        return new TUserroles(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserroles as(Name alias) {
        return new TUserroles(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserroles rename(String name) {
        return new TUserroles(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserroles rename(Name name) {
        return new TUserroles(name, null);
    }
}
