/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.wechatgame.jooq.db.routines;


import com.bsu.ugame.wechatgame.jooq.db.Login;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PSomedayhowmanydayleftrate extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1586681309;

    /**
     * The parameter <code>login.P_SomedayHowmanydayLeftRate.someday</code>.
     */
    public static final Parameter<String> SOMEDAY = createParameter("someday", org.jooq.impl.SQLDataType.VARCHAR(50), false, false);

    /**
     * The parameter <code>login.P_SomedayHowmanydayLeftRate.howmanyday</code>.
     */
    public static final Parameter<Integer> HOWMANYDAY = createParameter("howmanyday", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public PSomedayhowmanydayleftrate() {
        super("P_SomedayHowmanydayLeftRate", Login.LOGIN);

        addInParameter(SOMEDAY);
        addInParameter(HOWMANYDAY);
    }

    /**
     * Set the <code>someday</code> parameter IN value to the routine
     */
    public void setSomeday(String value) {
        setValue(SOMEDAY, value);
    }

    /**
     * Set the <code>howmanyday</code> parameter IN value to the routine
     */
    public void setHowmanyday(Integer value) {
        setValue(HOWMANYDAY, value);
    }
}
