/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.wechatgame.jooq.db.tables.records;


import com.bsu.ugame.wechatgame.jooq.db.tables.RBoxGame;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RBoxGameRecord extends UpdatableRecordImpl<RBoxGameRecord> implements Record3<UInteger, UInteger, UInteger> {

    private static final long serialVersionUID = -1868381059;

    /**
     * Setter for <code>login.r_box_game.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>login.r_box_game.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>login.r_box_game.boxid</code>. 盒子id
     */
    public void setBoxid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>login.r_box_game.boxid</code>. 盒子id
     */
    public UInteger getBoxid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>login.r_box_game.gameid</code>. 游戏id
     */
    public void setGameid(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>login.r_box_game.gameid</code>. 游戏id
     */
    public UInteger getGameid() {
        return (UInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UInteger> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UInteger> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return RBoxGame.R_BOX_GAME.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return RBoxGame.R_BOX_GAME.BOXID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return RBoxGame.R_BOX_GAME.GAMEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getBoxid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getGameid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getBoxid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getGameid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RBoxGameRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RBoxGameRecord value2(UInteger value) {
        setBoxid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RBoxGameRecord value3(UInteger value) {
        setGameid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RBoxGameRecord values(UInteger value1, UInteger value2, UInteger value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RBoxGameRecord
     */
    public RBoxGameRecord() {
        super(RBoxGame.R_BOX_GAME);
    }

    /**
     * Create a detached, initialised RBoxGameRecord
     */
    public RBoxGameRecord(UInteger id, UInteger boxid, UInteger gameid) {
        super(RBoxGame.R_BOX_GAME);

        set(0, id);
        set(1, boxid);
        set(2, gameid);
    }
}
