/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.wechatgame.jooq.db.tables.records;


import com.bsu.ugame.wechatgame.jooq.db.tables.RChannelauth3Game;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * 该表为auth为3的开发商对应表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RChannelauth3GameRecord extends UpdatableRecordImpl<RChannelauth3GameRecord> implements Record3<UInteger, UInteger, UInteger> {

    private static final long serialVersionUID = -1073077287;

    /**
     * Setter for <code>login.r_channelauth3_game.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>login.r_channelauth3_game.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>login.r_channelauth3_game.channelid</code>. 对应channel中auth为3的开发商用户
     */
    public void setChannelid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>login.r_channelauth3_game.channelid</code>. 对应channel中auth为3的开发商用户
     */
    public UInteger getChannelid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>login.r_channelauth3_game.gameid</code>. 对应的游戏id
     */
    public void setGameid(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>login.r_channelauth3_game.gameid</code>. 对应的游戏id
     */
    public UInteger getGameid() {
        return (UInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UInteger> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UInteger> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return RChannelauth3Game.R_CHANNELAUTH3_GAME.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return RChannelauth3Game.R_CHANNELAUTH3_GAME.CHANNELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return RChannelauth3Game.R_CHANNELAUTH3_GAME.GAMEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getChannelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getGameid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getChannelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getGameid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RChannelauth3GameRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RChannelauth3GameRecord value2(UInteger value) {
        setChannelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RChannelauth3GameRecord value3(UInteger value) {
        setGameid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RChannelauth3GameRecord values(UInteger value1, UInteger value2, UInteger value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RChannelauth3GameRecord
     */
    public RChannelauth3GameRecord() {
        super(RChannelauth3Game.R_CHANNELAUTH3_GAME);
    }

    /**
     * Create a detached, initialised RChannelauth3GameRecord
     */
    public RChannelauth3GameRecord(UInteger id, UInteger channelid, UInteger gameid) {
        super(RChannelauth3Game.R_CHANNELAUTH3_GAME);

        set(0, id);
        set(1, channelid);
        set(2, gameid);
    }
}
