/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.wechatgame.jooq.db.tables.records;


import com.bsu.ugame.wechatgame.jooq.db.tables.RChannelBox;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RChannelBoxRecord extends UpdatableRecordImpl<RChannelBoxRecord> implements Record3<UInteger, UInteger, UInteger> {

    private static final long serialVersionUID = -1101147776;

    /**
     * Setter for <code>login.r_channel_box.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>login.r_channel_box.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>login.r_channel_box.channelid</code>.
     */
    public void setChannelid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>login.r_channel_box.channelid</code>.
     */
    public UInteger getChannelid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>login.r_channel_box.boxid</code>. 来源盒子id
     */
    public void setBoxid(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>login.r_channel_box.boxid</code>. 来源盒子id
     */
    public UInteger getBoxid() {
        return (UInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UInteger> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, UInteger> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return RChannelBox.R_CHANNEL_BOX.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return RChannelBox.R_CHANNEL_BOX.CHANNELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return RChannelBox.R_CHANNEL_BOX.BOXID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getChannelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getBoxid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getChannelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getBoxid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RChannelBoxRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RChannelBoxRecord value2(UInteger value) {
        setChannelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RChannelBoxRecord value3(UInteger value) {
        setBoxid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RChannelBoxRecord values(UInteger value1, UInteger value2, UInteger value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RChannelBoxRecord
     */
    public RChannelBoxRecord() {
        super(RChannelBox.R_CHANNEL_BOX);
    }

    /**
     * Create a detached, initialised RChannelBoxRecord
     */
    public RChannelBoxRecord(UInteger id, UInteger channelid, UInteger boxid) {
        super(RChannelBox.R_CHANNEL_BOX);

        set(0, id);
        set(1, channelid);
        set(2, boxid);
    }
}
