/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.wechatgame.jooq.db.tables.records;


import com.bsu.ugame.wechatgame.jooq.db.tables.TGame;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TGameRecord extends UpdatableRecordImpl<TGameRecord> implements Record5<UInteger, String, String, String, Timestamp> {

    private static final long serialVersionUID = 1030423933;

    /**
     * Setter for <code>login.t_game.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>login.t_game.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>login.t_game.gamename</code>. 游戏名称
     */
    public void setGamename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>login.t_game.gamename</code>. 游戏名称
     */
    public String getGamename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>login.t_game.gameappid</code>. 小游戏的appid
     */
    public void setGameappid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>login.t_game.gameappid</code>. 小游戏的appid
     */
    public String getGameappid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>login.t_game.secrect</code>. 小游戏的secret
     */
    public void setSecrect(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>login.t_game.secrect</code>. 小游戏的secret
     */
    public String getSecrect() {
        return (String) get(3);
    }

    /**
     * Setter for <code>login.t_game.createTime</code>.
     */
    public void setCreatetime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>login.t_game.createTime</code>.
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, String, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, String, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TGame.T_GAME.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TGame.T_GAME.GAMENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TGame.T_GAME.GAMEAPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TGame.T_GAME.SECRECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return TGame.T_GAME.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGamename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getGameappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSecrect();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGamename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGameappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSecrect();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TGameRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TGameRecord value2(String value) {
        setGamename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TGameRecord value3(String value) {
        setGameappid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TGameRecord value4(String value) {
        setSecrect(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TGameRecord value5(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TGameRecord values(UInteger value1, String value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TGameRecord
     */
    public TGameRecord() {
        super(TGame.T_GAME);
    }

    /**
     * Create a detached, initialised TGameRecord
     */
    public TGameRecord(UInteger id, String gamename, String gameappid, String secrect, Timestamp createtime) {
        super(TGame.T_GAME);

        set(0, id);
        set(1, gamename);
        set(2, gameappid);
        set(3, secrect);
        set(4, createtime);
    }
}
