/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.wechatgame.jooq.db.tables.records;


import com.bsu.ugame.wechatgame.jooq.db.tables.TPlayergame;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * 玩家玩游戏产生的跟踪数据
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPlayergameRecord extends UpdatableRecordImpl<TPlayergameRecord> implements Record15<UInteger, String, String, String, String, String, String, Integer, String, String, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1788136990;

    /**
     * Setter for <code>login.t_playergame.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>login.t_playergame.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>login.t_playergame.gameappid</code>.
     */
    public void setGameappid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>login.t_playergame.gameappid</code>.
     */
    public String getGameappid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>login.t_playergame.recommendUser</code>. 记录玩家的推荐人openid
     */
    public void setRecommenduser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>login.t_playergame.recommendUser</code>. 记录玩家的推荐人openid
     */
    public String getRecommenduser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>login.t_playergame.openid</code>. 用户openid
     */
    public void setOpenid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>login.t_playergame.openid</code>. 用户openid
     */
    public String getOpenid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>login.t_playergame.boxappid</code>. 游戏来源渠道appid
     */
    public void setBoxappid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>login.t_playergame.boxappid</code>. 游戏来源渠道appid
     */
    public String getBoxappid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>login.t_playergame.currboxappid</code>. 当前的来源box的appid
     */
    public void setCurrboxappid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>login.t_playergame.currboxappid</code>. 当前的来源box的appid
     */
    public String getCurrboxappid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>login.t_playergame.nickname</code>.
     */
    public void setNickname(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>login.t_playergame.nickname</code>.
     */
    public String getNickname() {
        return (String) get(6);
    }

    /**
     * Setter for <code>login.t_playergame.gender</code>. 性别
     */
    public void setGender(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>login.t_playergame.gender</code>. 性别
     */
    public Integer getGender() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>login.t_playergame.country</code>.
     */
    public void setCountry(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>login.t_playergame.country</code>.
     */
    public String getCountry() {
        return (String) get(8);
    }

    /**
     * Setter for <code>login.t_playergame.city</code>. 城市
     */
    public void setCity(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>login.t_playergame.city</code>. 城市
     */
    public String getCity() {
        return (String) get(9);
    }

    /**
     * Setter for <code>login.t_playergame.province</code>. 省份
     */
    public void setProvince(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>login.t_playergame.province</code>. 省份
     */
    public String getProvince() {
        return (String) get(10);
    }

    /**
     * Setter for <code>login.t_playergame.language</code>. 语言
     */
    public void setLanguage(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>login.t_playergame.language</code>. 语言
     */
    public String getLanguage() {
        return (String) get(11);
    }

    /**
     * Setter for <code>login.t_playergame.avatarUrl</code>. 头像url
     */
    public void setAvatarurl(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>login.t_playergame.avatarUrl</code>. 头像url
     */
    public String getAvatarurl() {
        return (String) get(12);
    }

    /**
     * Setter for <code>login.t_playergame.createTime</code>. 创建时间
     */
    public void setCreatetime(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>login.t_playergame.createTime</code>. 创建时间
     */
    public Timestamp getCreatetime() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>login.t_playergame.lastLoginTime</code>. 玩家最后一次登录游戏时间
     */
    public void setLastlogintime(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>login.t_playergame.lastLoginTime</code>. 玩家最后一次登录游戏时间
     */
    public Timestamp getLastlogintime() {
        return (Timestamp) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<UInteger, String, String, String, String, String, String, Integer, String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<UInteger, String, String, String, String, String, String, Integer, String, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return TPlayergame.T_PLAYERGAME.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TPlayergame.T_PLAYERGAME.GAMEAPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TPlayergame.T_PLAYERGAME.RECOMMENDUSER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TPlayergame.T_PLAYERGAME.OPENID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TPlayergame.T_PLAYERGAME.BOXAPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TPlayergame.T_PLAYERGAME.CURRBOXAPPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TPlayergame.T_PLAYERGAME.NICKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TPlayergame.T_PLAYERGAME.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return TPlayergame.T_PLAYERGAME.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return TPlayergame.T_PLAYERGAME.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return TPlayergame.T_PLAYERGAME.PROVINCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return TPlayergame.T_PLAYERGAME.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return TPlayergame.T_PLAYERGAME.AVATARURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return TPlayergame.T_PLAYERGAME.CREATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return TPlayergame.T_PLAYERGAME.LASTLOGINTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGameappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRecommenduser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getBoxappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCurrboxappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getAvatarurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component15() {
        return getLastlogintime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGameappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRecommenduser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getBoxappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCurrboxappid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getAvatarurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getCreatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getLastlogintime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value2(String value) {
        setGameappid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value3(String value) {
        setRecommenduser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value4(String value) {
        setOpenid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value5(String value) {
        setBoxappid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value6(String value) {
        setCurrboxappid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value7(String value) {
        setNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value8(Integer value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value9(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value10(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value11(String value) {
        setProvince(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value12(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value13(String value) {
        setAvatarurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value14(Timestamp value) {
        setCreatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord value15(Timestamp value) {
        setLastlogintime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergameRecord values(UInteger value1, String value2, String value3, String value4, String value5, String value6, String value7, Integer value8, String value9, String value10, String value11, String value12, String value13, Timestamp value14, Timestamp value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TPlayergameRecord
     */
    public TPlayergameRecord() {
        super(TPlayergame.T_PLAYERGAME);
    }

    /**
     * Create a detached, initialised TPlayergameRecord
     */
    public TPlayergameRecord(UInteger id, String gameappid, String recommenduser, String openid, String boxappid, String currboxappid, String nickname, Integer gender, String country, String city, String province, String language, String avatarurl, Timestamp createtime, Timestamp lastlogintime) {
        super(TPlayergame.T_PLAYERGAME);

        set(0, id);
        set(1, gameappid);
        set(2, recommenduser);
        set(3, openid);
        set(4, boxappid);
        set(5, currboxappid);
        set(6, nickname);
        set(7, gender);
        set(8, country);
        set(9, city);
        set(10, province);
        set(11, language);
        set(12, avatarurl);
        set(13, createtime);
        set(14, lastlogintime);
    }
}
