/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.wechatgame.jooq.db.tables;


import com.bsu.ugame.wechatgame.jooq.db.Indexes;
import com.bsu.ugame.wechatgame.jooq.db.Keys;
import com.bsu.ugame.wechatgame.jooq.db.Login;
import com.bsu.ugame.wechatgame.jooq.db.tables.records.RChannelauth3GameRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * 该表为auth为3的开发商对应表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RChannelauth3Game extends TableImpl<RChannelauth3GameRecord> {

    private static final long serialVersionUID = -143137046;

    /**
     * The reference instance of <code>login.r_channelauth3_game</code>
     */
    public static final RChannelauth3Game R_CHANNELAUTH3_GAME = new RChannelauth3Game();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RChannelauth3GameRecord> getRecordType() {
        return RChannelauth3GameRecord.class;
    }

    /**
     * The column <code>login.r_channelauth3_game.id</code>.
     */
    public final TableField<RChannelauth3GameRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>login.r_channelauth3_game.channelid</code>. 对应channel中auth为3的开发商用户
     */
    public final TableField<RChannelauth3GameRecord, UInteger> CHANNELID = createField("channelid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "对应channel中auth为3的开发商用户");

    /**
     * The column <code>login.r_channelauth3_game.gameid</code>. 对应的游戏id
     */
    public final TableField<RChannelauth3GameRecord, UInteger> GAMEID = createField("gameid", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "对应的游戏id");

    /**
     * Create a <code>login.r_channelauth3_game</code> table reference
     */
    public RChannelauth3Game() {
        this(DSL.name("r_channelauth3_game"), null);
    }

    /**
     * Create an aliased <code>login.r_channelauth3_game</code> table reference
     */
    public RChannelauth3Game(String alias) {
        this(DSL.name(alias), R_CHANNELAUTH3_GAME);
    }

    /**
     * Create an aliased <code>login.r_channelauth3_game</code> table reference
     */
    public RChannelauth3Game(Name alias) {
        this(alias, R_CHANNELAUTH3_GAME);
    }

    private RChannelauth3Game(Name alias, Table<RChannelauth3GameRecord> aliased) {
        this(alias, aliased, null);
    }

    private RChannelauth3Game(Name alias, Table<RChannelauth3GameRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "该表为auth为3的开发商对应表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Login.LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.R_CHANNELAUTH3_GAME_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RChannelauth3GameRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_R_CHANNELAUTH3_GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RChannelauth3GameRecord> getPrimaryKey() {
        return Keys.KEY_R_CHANNELAUTH3_GAME_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RChannelauth3GameRecord>> getKeys() {
        return Arrays.<UniqueKey<RChannelauth3GameRecord>>asList(Keys.KEY_R_CHANNELAUTH3_GAME_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RChannelauth3Game as(String alias) {
        return new RChannelauth3Game(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RChannelauth3Game as(Name alias) {
        return new RChannelauth3Game(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RChannelauth3Game rename(String name) {
        return new RChannelauth3Game(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RChannelauth3Game rename(Name name) {
        return new RChannelauth3Game(name, null);
    }
}
