/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.wechatgame.jooq.db.tables;


import com.bsu.ugame.wechatgame.jooq.db.Indexes;
import com.bsu.ugame.wechatgame.jooq.db.Keys;
import com.bsu.ugame.wechatgame.jooq.db.Login;
import com.bsu.ugame.wechatgame.jooq.db.tables.records.TChannelRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TChannel extends TableImpl<TChannelRecord> {

    private static final long serialVersionUID = 1417617319;

    /**
     * The reference instance of <code>login.t_channel</code>
     */
    public static final TChannel T_CHANNEL = new TChannel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TChannelRecord> getRecordType() {
        return TChannelRecord.class;
    }

    /**
     * The column <code>login.t_channel.id</code>.
     */
    public final TableField<TChannelRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>login.t_channel.channelname</code>. 渠道名称
     */
    public final TableField<TChannelRecord, String> CHANNELNAME = createField("channelname", org.jooq.impl.SQLDataType.VARCHAR(64), this, "渠道名称");

    /**
     * The column <code>login.t_channel.account</code>. 渠道登录账号
     */
    public final TableField<TChannelRecord, String> ACCOUNT = createField("account", org.jooq.impl.SQLDataType.VARCHAR(64), this, "渠道登录账号");

    /**
     * The column <code>login.t_channel.password</code>. 登录密码
     */
    public final TableField<TChannelRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR(32), this, "登录密码");

    /**
     * The column <code>login.t_channel.email</code>. 渠道邮箱
     */
    public final TableField<TChannelRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(32), this, "渠道邮箱");

    /**
     * The column <code>login.t_channel.phone</code>. 渠道联系电话
     */
    public final TableField<TChannelRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(16), this, "渠道联系电话");

    /**
     * The column <code>login.t_channel.auth</code>. 渠道权限 1:管理员 2:运营商 3:开发商
     */
    public final TableField<TChannelRecord, String> AUTH = createField("auth", org.jooq.impl.SQLDataType.VARCHAR(16), this, "渠道权限 1:管理员 2:运营商 3:开发商");

    /**
     * Create a <code>login.t_channel</code> table reference
     */
    public TChannel() {
        this(DSL.name("t_channel"), null);
    }

    /**
     * Create an aliased <code>login.t_channel</code> table reference
     */
    public TChannel(String alias) {
        this(DSL.name(alias), T_CHANNEL);
    }

    /**
     * Create an aliased <code>login.t_channel</code> table reference
     */
    public TChannel(Name alias) {
        this(alias, T_CHANNEL);
    }

    private TChannel(Name alias, Table<TChannelRecord> aliased) {
        this(alias, aliased, null);
    }

    private TChannel(Name alias, Table<TChannelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Login.LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_CHANNEL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TChannelRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_T_CHANNEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TChannelRecord> getPrimaryKey() {
        return Keys.KEY_T_CHANNEL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TChannelRecord>> getKeys() {
        return Arrays.<UniqueKey<TChannelRecord>>asList(Keys.KEY_T_CHANNEL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TChannel as(String alias) {
        return new TChannel(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TChannel as(Name alias) {
        return new TChannel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TChannel rename(String name) {
        return new TChannel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TChannel rename(Name name) {
        return new TChannel(name, null);
    }
}
