/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.wechatgame.jooq.db.tables;


import com.bsu.ugame.wechatgame.jooq.db.Indexes;
import com.bsu.ugame.wechatgame.jooq.db.Keys;
import com.bsu.ugame.wechatgame.jooq.db.Login;
import com.bsu.ugame.wechatgame.jooq.db.tables.records.TPlayergameRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * 玩家玩游戏产生的跟踪数据
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TPlayergame extends TableImpl<TPlayergameRecord> {

    private static final long serialVersionUID = -868690957;

    /**
     * The reference instance of <code>login.t_playergame</code>
     */
    public static final TPlayergame T_PLAYERGAME = new TPlayergame();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TPlayergameRecord> getRecordType() {
        return TPlayergameRecord.class;
    }

    /**
     * The column <code>login.t_playergame.id</code>.
     */
    public final TableField<TPlayergameRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>login.t_playergame.gameappid</code>.
     */
    public final TableField<TPlayergameRecord, String> GAMEAPPID = createField("gameappid", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>login.t_playergame.recommendUser</code>. 记录玩家的推荐人openid
     */
    public final TableField<TPlayergameRecord, String> RECOMMENDUSER = createField("recommendUser", org.jooq.impl.SQLDataType.VARCHAR(50), this, "记录玩家的推荐人openid");

    /**
     * The column <code>login.t_playergame.openid</code>. 用户openid
     */
    public final TableField<TPlayergameRecord, String> OPENID = createField("openid", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "用户openid");

    /**
     * The column <code>login.t_playergame.boxappid</code>. 游戏来源渠道appid
     */
    public final TableField<TPlayergameRecord, String> BOXAPPID = createField("boxappid", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "游戏来源渠道appid");

    /**
     * The column <code>login.t_playergame.currboxappid</code>. 当前的来源box的appid
     */
    public final TableField<TPlayergameRecord, String> CURRBOXAPPID = createField("currboxappid", org.jooq.impl.SQLDataType.VARCHAR(50), this, "当前的来源box的appid");

    /**
     * The column <code>login.t_playergame.nickname</code>.
     */
    public final TableField<TPlayergameRecord, String> NICKNAME = createField("nickname", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>login.t_playergame.gender</code>. 性别
     */
    public final TableField<TPlayergameRecord, Integer> GENDER = createField("gender", org.jooq.impl.SQLDataType.INTEGER, this, "性别");

    /**
     * The column <code>login.t_playergame.country</code>.
     */
    public final TableField<TPlayergameRecord, String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>login.t_playergame.city</code>. 城市
     */
    public final TableField<TPlayergameRecord, String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR(20), this, "城市");

    /**
     * The column <code>login.t_playergame.province</code>. 省份
     */
    public final TableField<TPlayergameRecord, String> PROVINCE = createField("province", org.jooq.impl.SQLDataType.VARCHAR(40), this, "省份");

    /**
     * The column <code>login.t_playergame.language</code>. 语言
     */
    public final TableField<TPlayergameRecord, String> LANGUAGE = createField("language", org.jooq.impl.SQLDataType.VARCHAR(10), this, "语言");

    /**
     * The column <code>login.t_playergame.avatarUrl</code>. 头像url
     */
    public final TableField<TPlayergameRecord, String> AVATARURL = createField("avatarUrl", org.jooq.impl.SQLDataType.VARCHAR(300), this, "头像url");

    /**
     * The column <code>login.t_playergame.createTime</code>. 创建时间
     */
    public final TableField<TPlayergameRecord, Timestamp> CREATETIME = createField("createTime", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>login.t_playergame.lastLoginTime</code>. 玩家最后一次登录游戏时间
     */
    public final TableField<TPlayergameRecord, Timestamp> LASTLOGINTIME = createField("lastLoginTime", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "玩家最后一次登录游戏时间");

    /**
     * Create a <code>login.t_playergame</code> table reference
     */
    public TPlayergame() {
        this(DSL.name("t_playergame"), null);
    }

    /**
     * Create an aliased <code>login.t_playergame</code> table reference
     */
    public TPlayergame(String alias) {
        this(DSL.name(alias), T_PLAYERGAME);
    }

    /**
     * Create an aliased <code>login.t_playergame</code> table reference
     */
    public TPlayergame(Name alias) {
        this(alias, T_PLAYERGAME);
    }

    private TPlayergame(Name alias, Table<TPlayergameRecord> aliased) {
        this(alias, aliased, null);
    }

    private TPlayergame(Name alias, Table<TPlayergameRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "玩家玩游戏产生的跟踪数据");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Login.LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_PLAYERGAME_IDX_BOXAPPID, Indexes.T_PLAYERGAME_IDX_GAMEAPPID, Indexes.T_PLAYERGAME_PRIMARY, Indexes.T_PLAYERGAME_UNI_GAMEAPPID_OPENID_BOXAPPID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TPlayergameRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_T_PLAYERGAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TPlayergameRecord> getPrimaryKey() {
        return Keys.KEY_T_PLAYERGAME_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TPlayergameRecord>> getKeys() {
        return Arrays.<UniqueKey<TPlayergameRecord>>asList(Keys.KEY_T_PLAYERGAME_PRIMARY, Keys.KEY_T_PLAYERGAME_UNI_GAMEAPPID_OPENID_BOXAPPID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergame as(String alias) {
        return new TPlayergame(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TPlayergame as(Name alias) {
        return new TPlayergame(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TPlayergame rename(String name) {
        return new TPlayergame(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TPlayergame rename(Name name) {
        return new TPlayergame(name, null);
    }
}
