/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.gameparams.jooq.db;


import com.bsu.ugame.gameparams.jooq.db.tables.RUserGame;
import com.bsu.ugame.gameparams.jooq.db.tables.TControl;
import com.bsu.ugame.gameparams.jooq.db.tables.TControlvalue;
import com.bsu.ugame.gameparams.jooq.db.tables.TGame;
import com.bsu.ugame.gameparams.jooq.db.tables.THelpdata;
import com.bsu.ugame.gameparams.jooq.db.tables.TJumpdata;
import com.bsu.ugame.gameparams.jooq.db.tables.TMoregames;
import com.bsu.ugame.gameparams.jooq.db.tables.TMorejump;
import com.bsu.ugame.gameparams.jooq.db.tables.TPlayer;
import com.bsu.ugame.gameparams.jooq.db.tables.TRolespermissions;
import com.bsu.ugame.gameparams.jooq.db.tables.TShare;
import com.bsu.ugame.gameparams.jooq.db.tables.TUser;
import com.bsu.ugame.gameparams.jooq.db.tables.TUserroles;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in gameparams
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>gameparams.r_user_game</code>.
     */
    public static final RUserGame R_USER_GAME = com.bsu.ugame.gameparams.jooq.db.tables.RUserGame.R_USER_GAME;

    /**
     * The table <code>gameparams.t_control</code>.
     */
    public static final TControl T_CONTROL = com.bsu.ugame.gameparams.jooq.db.tables.TControl.T_CONTROL;

    /**
     * The table <code>gameparams.t_controlvalue</code>.
     */
    public static final TControlvalue T_CONTROLVALUE = com.bsu.ugame.gameparams.jooq.db.tables.TControlvalue.T_CONTROLVALUE;

    /**
     * 保存游戏信息。产品的基础信息。
     */
    public static final TGame T_GAME = com.bsu.ugame.gameparams.jooq.db.tables.TGame.T_GAME;

    /**
     * The table <code>gameparams.t_helpdata</code>.
     */
    public static final THelpdata T_HELPDATA = com.bsu.ugame.gameparams.jooq.db.tables.THelpdata.T_HELPDATA;

    /**
     * The table <code>gameparams.t_jumpdata</code>.
     */
    public static final TJumpdata T_JUMPDATA = com.bsu.ugame.gameparams.jooq.db.tables.TJumpdata.T_JUMPDATA;

    /**
     * The table <code>gameparams.t_moregames</code>.
     */
    public static final TMoregames T_MOREGAMES = com.bsu.ugame.gameparams.jooq.db.tables.TMoregames.T_MOREGAMES;

    /**
     * The table <code>gameparams.t_morejump</code>.
     */
    public static final TMorejump T_MOREJUMP = com.bsu.ugame.gameparams.jooq.db.tables.TMorejump.T_MOREJUMP;

    /**
     * The table <code>gameparams.t_player</code>.
     */
    public static final TPlayer T_PLAYER = com.bsu.ugame.gameparams.jooq.db.tables.TPlayer.T_PLAYER;

    /**
     * The table <code>gameparams.t_rolespermissions</code>.
     */
    public static final TRolespermissions T_ROLESPERMISSIONS = com.bsu.ugame.gameparams.jooq.db.tables.TRolespermissions.T_ROLESPERMISSIONS;

    /**
     * The table <code>gameparams.t_share</code>.
     */
    public static final TShare T_SHARE = com.bsu.ugame.gameparams.jooq.db.tables.TShare.T_SHARE;

    /**
     * The table <code>gameparams.t_user</code>.
     */
    public static final TUser T_USER = com.bsu.ugame.gameparams.jooq.db.tables.TUser.T_USER;

    /**
     * The table <code>gameparams.t_userroles</code>.
     */
    public static final TUserroles T_USERROLES = com.bsu.ugame.gameparams.jooq.db.tables.TUserroles.T_USERROLES;
}
