/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.wechatgame.jooq.db;


import com.bsu.ugame.wechatgame.jooq.db.tables.RBoxGame;
import com.bsu.ugame.wechatgame.jooq.db.tables.RChannelBox;
import com.bsu.ugame.wechatgame.jooq.db.tables.RChannelauth3Game;
import com.bsu.ugame.wechatgame.jooq.db.tables.TBox;
import com.bsu.ugame.wechatgame.jooq.db.tables.TChannel;
import com.bsu.ugame.wechatgame.jooq.db.tables.TDailydata;
import com.bsu.ugame.wechatgame.jooq.db.tables.TGame;
import com.bsu.ugame.wechatgame.jooq.db.tables.THelpdata;
import com.bsu.ugame.wechatgame.jooq.db.tables.TPlayergame;
import com.bsu.ugame.wechatgame.jooq.db.tables.TPlayergameCopy;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>login</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index R_BOX_GAME_PRIMARY = Indexes0.R_BOX_GAME_PRIMARY;
    public static final Index R_CHANNELAUTH3_GAME_PRIMARY = Indexes0.R_CHANNELAUTH3_GAME_PRIMARY;
    public static final Index R_CHANNEL_BOX_PRIMARY = Indexes0.R_CHANNEL_BOX_PRIMARY;
    public static final Index T_BOX_PRIMARY = Indexes0.T_BOX_PRIMARY;
    public static final Index T_CHANNEL_PRIMARY = Indexes0.T_CHANNEL_PRIMARY;
    public static final Index T_DAILYDATA_PRIMARY = Indexes0.T_DAILYDATA_PRIMARY;
    public static final Index T_GAME_PRIMARY = Indexes0.T_GAME_PRIMARY;
    public static final Index T_HELPDATA_PRIMARY = Indexes0.T_HELPDATA_PRIMARY;
    public static final Index T_HELPDATA_UNI_GAMEAPPID_ORIGINATORID_HELPEDID = Indexes0.T_HELPDATA_UNI_GAMEAPPID_ORIGINATORID_HELPEDID;
    public static final Index T_PLAYERGAME_IDX_BOXAPPID = Indexes0.T_PLAYERGAME_IDX_BOXAPPID;
    public static final Index T_PLAYERGAME_IDX_GAMEAPPID = Indexes0.T_PLAYERGAME_IDX_GAMEAPPID;
    public static final Index T_PLAYERGAME_PRIMARY = Indexes0.T_PLAYERGAME_PRIMARY;
    public static final Index T_PLAYERGAME_UNI_GAMEAPPID_OPENID_BOXAPPID = Indexes0.T_PLAYERGAME_UNI_GAMEAPPID_OPENID_BOXAPPID;
    public static final Index T_PLAYERGAME_COPY_IDX_BOXAPPID = Indexes0.T_PLAYERGAME_COPY_IDX_BOXAPPID;
    public static final Index T_PLAYERGAME_COPY_IDX_GAMEAPPID = Indexes0.T_PLAYERGAME_COPY_IDX_GAMEAPPID;
    public static final Index T_PLAYERGAME_COPY_PRIMARY = Indexes0.T_PLAYERGAME_COPY_PRIMARY;
    public static final Index T_PLAYERGAME_COPY_UNI_OPENID_GAMEAPPID_BOXAPPID = Indexes0.T_PLAYERGAME_COPY_UNI_OPENID_GAMEAPPID_BOXAPPID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index R_BOX_GAME_PRIMARY = createIndex("PRIMARY", RBoxGame.R_BOX_GAME, new OrderField[] { RBoxGame.R_BOX_GAME.ID }, true);
        public static Index R_CHANNELAUTH3_GAME_PRIMARY = createIndex("PRIMARY", RChannelauth3Game.R_CHANNELAUTH3_GAME, new OrderField[] { RChannelauth3Game.R_CHANNELAUTH3_GAME.ID }, true);
        public static Index R_CHANNEL_BOX_PRIMARY = createIndex("PRIMARY", RChannelBox.R_CHANNEL_BOX, new OrderField[] { RChannelBox.R_CHANNEL_BOX.ID }, true);
        public static Index T_BOX_PRIMARY = createIndex("PRIMARY", TBox.T_BOX, new OrderField[] { TBox.T_BOX.ID }, true);
        public static Index T_CHANNEL_PRIMARY = createIndex("PRIMARY", TChannel.T_CHANNEL, new OrderField[] { TChannel.T_CHANNEL.ID }, true);
        public static Index T_DAILYDATA_PRIMARY = createIndex("PRIMARY", TDailydata.T_DAILYDATA, new OrderField[] { TDailydata.T_DAILYDATA.ID }, true);
        public static Index T_GAME_PRIMARY = createIndex("PRIMARY", TGame.T_GAME, new OrderField[] { TGame.T_GAME.ID }, true);
        public static Index T_HELPDATA_PRIMARY = createIndex("PRIMARY", THelpdata.T_HELPDATA, new OrderField[] { THelpdata.T_HELPDATA.ID }, true);
        public static Index T_HELPDATA_UNI_GAMEAPPID_ORIGINATORID_HELPEDID = createIndex("UNI_GAMEAPPID_ORIGINATORID_HELPEDID", THelpdata.T_HELPDATA, new OrderField[] { THelpdata.T_HELPDATA.GAMEAPPID, THelpdata.T_HELPDATA.ORIGINATORID, THelpdata.T_HELPDATA.HELPID }, true);
        public static Index T_PLAYERGAME_IDX_BOXAPPID = createIndex("IDX_BOXAPPID", TPlayergame.T_PLAYERGAME, new OrderField[] { TPlayergame.T_PLAYERGAME.BOXAPPID }, false);
        public static Index T_PLAYERGAME_IDX_GAMEAPPID = createIndex("IDX_GAMEAPPID", TPlayergame.T_PLAYERGAME, new OrderField[] { TPlayergame.T_PLAYERGAME.GAMEAPPID }, false);
        public static Index T_PLAYERGAME_PRIMARY = createIndex("PRIMARY", TPlayergame.T_PLAYERGAME, new OrderField[] { TPlayergame.T_PLAYERGAME.ID }, true);
        public static Index T_PLAYERGAME_UNI_GAMEAPPID_OPENID_BOXAPPID = createIndex("UNI_GAMEAPPID_OPENID_BOXAPPID", TPlayergame.T_PLAYERGAME, new OrderField[] { TPlayergame.T_PLAYERGAME.GAMEAPPID, TPlayergame.T_PLAYERGAME.OPENID, TPlayergame.T_PLAYERGAME.BOXAPPID }, true);
        public static Index T_PLAYERGAME_COPY_IDX_BOXAPPID = createIndex("IDX_BOXAPPID", TPlayergameCopy.T_PLAYERGAME_COPY, new OrderField[] { TPlayergameCopy.T_PLAYERGAME_COPY.BOXAPPID }, false);
        public static Index T_PLAYERGAME_COPY_IDX_GAMEAPPID = createIndex("IDX_GAMEAPPID", TPlayergameCopy.T_PLAYERGAME_COPY, new OrderField[] { TPlayergameCopy.T_PLAYERGAME_COPY.GAMEAPPID }, false);
        public static Index T_PLAYERGAME_COPY_PRIMARY = createIndex("PRIMARY", TPlayergameCopy.T_PLAYERGAME_COPY, new OrderField[] { TPlayergameCopy.T_PLAYERGAME_COPY.ID }, true);
        public static Index T_PLAYERGAME_COPY_UNI_OPENID_GAMEAPPID_BOXAPPID = createIndex("UNI_OPENID_GAMEAPPID_BOXAPPID", TPlayergameCopy.T_PLAYERGAME_COPY, new OrderField[] { TPlayergameCopy.T_PLAYERGAME_COPY.GAMEAPPID, TPlayergameCopy.T_PLAYERGAME_COPY.OPENID, TPlayergameCopy.T_PLAYERGAME_COPY.BOXAPPID }, true);
    }
}
