/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.wechatgame.jooq.db;


import com.bsu.ugame.wechatgame.jooq.db.tables.RBoxGame;
import com.bsu.ugame.wechatgame.jooq.db.tables.RChannelBox;
import com.bsu.ugame.wechatgame.jooq.db.tables.RChannelauth3Game;
import com.bsu.ugame.wechatgame.jooq.db.tables.TBox;
import com.bsu.ugame.wechatgame.jooq.db.tables.TChannel;
import com.bsu.ugame.wechatgame.jooq.db.tables.TDailydata;
import com.bsu.ugame.wechatgame.jooq.db.tables.TGame;
import com.bsu.ugame.wechatgame.jooq.db.tables.THelpdata;
import com.bsu.ugame.wechatgame.jooq.db.tables.TPlayergame;
import com.bsu.ugame.wechatgame.jooq.db.tables.TPlayergameCopy;
import com.bsu.ugame.wechatgame.jooq.db.tables.records.RBoxGameRecord;
import com.bsu.ugame.wechatgame.jooq.db.tables.records.RChannelBoxRecord;
import com.bsu.ugame.wechatgame.jooq.db.tables.records.RChannelauth3GameRecord;
import com.bsu.ugame.wechatgame.jooq.db.tables.records.TBoxRecord;
import com.bsu.ugame.wechatgame.jooq.db.tables.records.TChannelRecord;
import com.bsu.ugame.wechatgame.jooq.db.tables.records.TDailydataRecord;
import com.bsu.ugame.wechatgame.jooq.db.tables.records.TGameRecord;
import com.bsu.ugame.wechatgame.jooq.db.tables.records.THelpdataRecord;
import com.bsu.ugame.wechatgame.jooq.db.tables.records.TPlayergameCopyRecord;
import com.bsu.ugame.wechatgame.jooq.db.tables.records.TPlayergameRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>login</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RBoxGameRecord, UInteger> IDENTITY_R_BOX_GAME = Identities0.IDENTITY_R_BOX_GAME;
    public static final Identity<RChannelauth3GameRecord, UInteger> IDENTITY_R_CHANNELAUTH3_GAME = Identities0.IDENTITY_R_CHANNELAUTH3_GAME;
    public static final Identity<RChannelBoxRecord, UInteger> IDENTITY_R_CHANNEL_BOX = Identities0.IDENTITY_R_CHANNEL_BOX;
    public static final Identity<TBoxRecord, UInteger> IDENTITY_T_BOX = Identities0.IDENTITY_T_BOX;
    public static final Identity<TChannelRecord, UInteger> IDENTITY_T_CHANNEL = Identities0.IDENTITY_T_CHANNEL;
    public static final Identity<TDailydataRecord, UInteger> IDENTITY_T_DAILYDATA = Identities0.IDENTITY_T_DAILYDATA;
    public static final Identity<TGameRecord, UInteger> IDENTITY_T_GAME = Identities0.IDENTITY_T_GAME;
    public static final Identity<THelpdataRecord, UInteger> IDENTITY_T_HELPDATA = Identities0.IDENTITY_T_HELPDATA;
    public static final Identity<TPlayergameRecord, UInteger> IDENTITY_T_PLAYERGAME = Identities0.IDENTITY_T_PLAYERGAME;
    public static final Identity<TPlayergameCopyRecord, UInteger> IDENTITY_T_PLAYERGAME_COPY = Identities0.IDENTITY_T_PLAYERGAME_COPY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RBoxGameRecord> KEY_R_BOX_GAME_PRIMARY = UniqueKeys0.KEY_R_BOX_GAME_PRIMARY;
    public static final UniqueKey<RChannelauth3GameRecord> KEY_R_CHANNELAUTH3_GAME_PRIMARY = UniqueKeys0.KEY_R_CHANNELAUTH3_GAME_PRIMARY;
    public static final UniqueKey<RChannelBoxRecord> KEY_R_CHANNEL_BOX_PRIMARY = UniqueKeys0.KEY_R_CHANNEL_BOX_PRIMARY;
    public static final UniqueKey<TBoxRecord> KEY_T_BOX_PRIMARY = UniqueKeys0.KEY_T_BOX_PRIMARY;
    public static final UniqueKey<TChannelRecord> KEY_T_CHANNEL_PRIMARY = UniqueKeys0.KEY_T_CHANNEL_PRIMARY;
    public static final UniqueKey<TDailydataRecord> KEY_T_DAILYDATA_PRIMARY = UniqueKeys0.KEY_T_DAILYDATA_PRIMARY;
    public static final UniqueKey<TGameRecord> KEY_T_GAME_PRIMARY = UniqueKeys0.KEY_T_GAME_PRIMARY;
    public static final UniqueKey<THelpdataRecord> KEY_T_HELPDATA_PRIMARY = UniqueKeys0.KEY_T_HELPDATA_PRIMARY;
    public static final UniqueKey<THelpdataRecord> KEY_T_HELPDATA_UNI_GAMEAPPID_ORIGINATORID_HELPEDID = UniqueKeys0.KEY_T_HELPDATA_UNI_GAMEAPPID_ORIGINATORID_HELPEDID;
    public static final UniqueKey<TPlayergameRecord> KEY_T_PLAYERGAME_PRIMARY = UniqueKeys0.KEY_T_PLAYERGAME_PRIMARY;
    public static final UniqueKey<TPlayergameRecord> KEY_T_PLAYERGAME_UNI_GAMEAPPID_OPENID_BOXAPPID = UniqueKeys0.KEY_T_PLAYERGAME_UNI_GAMEAPPID_OPENID_BOXAPPID;
    public static final UniqueKey<TPlayergameCopyRecord> KEY_T_PLAYERGAME_COPY_PRIMARY = UniqueKeys0.KEY_T_PLAYERGAME_COPY_PRIMARY;
    public static final UniqueKey<TPlayergameCopyRecord> KEY_T_PLAYERGAME_COPY_UNI_OPENID_GAMEAPPID_BOXAPPID = UniqueKeys0.KEY_T_PLAYERGAME_COPY_UNI_OPENID_GAMEAPPID_BOXAPPID;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<RBoxGameRecord, UInteger> IDENTITY_R_BOX_GAME = createIdentity(RBoxGame.R_BOX_GAME, RBoxGame.R_BOX_GAME.ID);
        public static Identity<RChannelauth3GameRecord, UInteger> IDENTITY_R_CHANNELAUTH3_GAME = createIdentity(RChannelauth3Game.R_CHANNELAUTH3_GAME, RChannelauth3Game.R_CHANNELAUTH3_GAME.ID);
        public static Identity<RChannelBoxRecord, UInteger> IDENTITY_R_CHANNEL_BOX = createIdentity(RChannelBox.R_CHANNEL_BOX, RChannelBox.R_CHANNEL_BOX.ID);
        public static Identity<TBoxRecord, UInteger> IDENTITY_T_BOX = createIdentity(TBox.T_BOX, TBox.T_BOX.ID);
        public static Identity<TChannelRecord, UInteger> IDENTITY_T_CHANNEL = createIdentity(TChannel.T_CHANNEL, TChannel.T_CHANNEL.ID);
        public static Identity<TDailydataRecord, UInteger> IDENTITY_T_DAILYDATA = createIdentity(TDailydata.T_DAILYDATA, TDailydata.T_DAILYDATA.ID);
        public static Identity<TGameRecord, UInteger> IDENTITY_T_GAME = createIdentity(TGame.T_GAME, TGame.T_GAME.ID);
        public static Identity<THelpdataRecord, UInteger> IDENTITY_T_HELPDATA = createIdentity(THelpdata.T_HELPDATA, THelpdata.T_HELPDATA.ID);
        public static Identity<TPlayergameRecord, UInteger> IDENTITY_T_PLAYERGAME = createIdentity(TPlayergame.T_PLAYERGAME, TPlayergame.T_PLAYERGAME.ID);
        public static Identity<TPlayergameCopyRecord, UInteger> IDENTITY_T_PLAYERGAME_COPY = createIdentity(TPlayergameCopy.T_PLAYERGAME_COPY, TPlayergameCopy.T_PLAYERGAME_COPY.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<RBoxGameRecord> KEY_R_BOX_GAME_PRIMARY = createUniqueKey(RBoxGame.R_BOX_GAME, "KEY_r_box_game_PRIMARY", RBoxGame.R_BOX_GAME.ID);
        public static final UniqueKey<RChannelauth3GameRecord> KEY_R_CHANNELAUTH3_GAME_PRIMARY = createUniqueKey(RChannelauth3Game.R_CHANNELAUTH3_GAME, "KEY_r_channelauth3_game_PRIMARY", RChannelauth3Game.R_CHANNELAUTH3_GAME.ID);
        public static final UniqueKey<RChannelBoxRecord> KEY_R_CHANNEL_BOX_PRIMARY = createUniqueKey(RChannelBox.R_CHANNEL_BOX, "KEY_r_channel_box_PRIMARY", RChannelBox.R_CHANNEL_BOX.ID);
        public static final UniqueKey<TBoxRecord> KEY_T_BOX_PRIMARY = createUniqueKey(TBox.T_BOX, "KEY_t_box_PRIMARY", TBox.T_BOX.ID);
        public static final UniqueKey<TChannelRecord> KEY_T_CHANNEL_PRIMARY = createUniqueKey(TChannel.T_CHANNEL, "KEY_t_channel_PRIMARY", TChannel.T_CHANNEL.ID);
        public static final UniqueKey<TDailydataRecord> KEY_T_DAILYDATA_PRIMARY = createUniqueKey(TDailydata.T_DAILYDATA, "KEY_t_dailydata_PRIMARY", TDailydata.T_DAILYDATA.ID);
        public static final UniqueKey<TGameRecord> KEY_T_GAME_PRIMARY = createUniqueKey(TGame.T_GAME, "KEY_t_game_PRIMARY", TGame.T_GAME.ID);
        public static final UniqueKey<THelpdataRecord> KEY_T_HELPDATA_PRIMARY = createUniqueKey(THelpdata.T_HELPDATA, "KEY_t_helpdata_PRIMARY", THelpdata.T_HELPDATA.ID);
        public static final UniqueKey<THelpdataRecord> KEY_T_HELPDATA_UNI_GAMEAPPID_ORIGINATORID_HELPEDID = createUniqueKey(THelpdata.T_HELPDATA, "KEY_t_helpdata_UNI_GAMEAPPID_ORIGINATORID_HELPEDID", THelpdata.T_HELPDATA.GAMEAPPID, THelpdata.T_HELPDATA.ORIGINATORID, THelpdata.T_HELPDATA.HELPID);
        public static final UniqueKey<TPlayergameRecord> KEY_T_PLAYERGAME_PRIMARY = createUniqueKey(TPlayergame.T_PLAYERGAME, "KEY_t_playergame_PRIMARY", TPlayergame.T_PLAYERGAME.ID);
        public static final UniqueKey<TPlayergameRecord> KEY_T_PLAYERGAME_UNI_GAMEAPPID_OPENID_BOXAPPID = createUniqueKey(TPlayergame.T_PLAYERGAME, "KEY_t_playergame_UNI_GAMEAPPID_OPENID_BOXAPPID", TPlayergame.T_PLAYERGAME.GAMEAPPID, TPlayergame.T_PLAYERGAME.OPENID, TPlayergame.T_PLAYERGAME.BOXAPPID);
        public static final UniqueKey<TPlayergameCopyRecord> KEY_T_PLAYERGAME_COPY_PRIMARY = createUniqueKey(TPlayergameCopy.T_PLAYERGAME_COPY, "KEY_t_playergame_copy_PRIMARY", TPlayergameCopy.T_PLAYERGAME_COPY.ID);
        public static final UniqueKey<TPlayergameCopyRecord> KEY_T_PLAYERGAME_COPY_UNI_OPENID_GAMEAPPID_BOXAPPID = createUniqueKey(TPlayergameCopy.T_PLAYERGAME_COPY, "KEY_t_playergame_copy_UNI_OPENID_GAMEAPPID_BOXAPPID", TPlayergameCopy.T_PLAYERGAME_COPY.GAMEAPPID, TPlayergameCopy.T_PLAYERGAME_COPY.OPENID, TPlayergameCopy.T_PLAYERGAME_COPY.BOXAPPID);
    }
}
