/*
 * This file is generated by jOOQ.
*/
package com.bsu.ugame.wechatgame.jooq.db;


import com.bsu.ugame.wechatgame.jooq.db.routines.FunLeftrate;
import com.bsu.ugame.wechatgame.jooq.db.routines.PAddmissdata;
import com.bsu.ugame.wechatgame.jooq.db.routines.PCheckunknownbox;
import com.bsu.ugame.wechatgame.jooq.db.routines.PComputernextdayleftrate;
import com.bsu.ugame.wechatgame.jooq.db.routines.PComputersevendaysleftrate;
import com.bsu.ugame.wechatgame.jooq.db.routines.PComputerthreedaysleftrate;
import com.bsu.ugame.wechatgame.jooq.db.routines.PSomedayhowmanydayleftrate;
import com.bsu.ugame.wechatgame.jooq.db.routines.PUsername;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in login
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>login.Fun_LeftRate</code>
     */
    public static BigDecimal funLeftrate(Configuration configuration, String padddate, Integer plefttype, String pboxappid, String pgameappid) {
        FunLeftrate f = new FunLeftrate();
        f.setPadddate(padddate);
        f.setPlefttype(plefttype);
        f.setPboxappid(pboxappid);
        f.setPgameappid(pgameappid);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>login.Fun_LeftRate</code> as a field.
     */
    public static Field<BigDecimal> funLeftrate(String padddate, Integer plefttype, String pboxappid, String pgameappid) {
        FunLeftrate f = new FunLeftrate();
        f.setPadddate(padddate);
        f.setPlefttype(plefttype);
        f.setPboxappid(pboxappid);
        f.setPgameappid(pgameappid);

        return f.asField();
    }

    /**
     * Get <code>login.Fun_LeftRate</code> as a field.
     */
    public static Field<BigDecimal> funLeftrate(Field<String> padddate, Field<Integer> plefttype, Field<String> pboxappid, Field<String> pgameappid) {
        FunLeftrate f = new FunLeftrate();
        f.setPadddate(padddate);
        f.setPlefttype(plefttype);
        f.setPboxappid(pboxappid);
        f.setPgameappid(pgameappid);

        return f.asField();
    }

    /**
     * Call <code>login.P_AddMissData</code>
     */
    public static void pAddmissdata(Configuration configuration, String someday) {
        PAddmissdata p = new PAddmissdata();
        p.setSomeday(someday);

        p.execute(configuration);
    }

    /**
     * Call <code>login.P_CheckUnknownBox</code>
     */
    public static void pCheckunknownbox(Configuration configuration) {
        PCheckunknownbox p = new PCheckunknownbox();

        p.execute(configuration);
    }

    /**
     * Call <code>login.P_ComputerNextDayLeftRate</code>
     */
    public static void pComputernextdayleftrate(Configuration configuration) {
        PComputernextdayleftrate p = new PComputernextdayleftrate();

        p.execute(configuration);
    }

    /**
     * Call <code>login.P_ComputerSevenDaysLeftRate</code>
     */
    public static void pComputersevendaysleftrate(Configuration configuration) {
        PComputersevendaysleftrate p = new PComputersevendaysleftrate();

        p.execute(configuration);
    }

    /**
     * Call <code>login.P_ComputerThreeDaysLeftRate</code>
     */
    public static void pComputerthreedaysleftrate(Configuration configuration) {
        PComputerthreedaysleftrate p = new PComputerthreedaysleftrate();

        p.execute(configuration);
    }

    /**
     * Call <code>login.P_SomedayHowmanydayLeftRate</code>
     */
    public static void pSomedayhowmanydayleftrate(Configuration configuration, String someday, Integer howmanyday) {
        PSomedayhowmanydayleftrate p = new PSomedayhowmanydayleftrate();
        p.setSomeday(someday);
        p.setHowmanyday(howmanyday);

        p.execute(configuration);
    }

    /**
     * Call <code>login.P_UserName</code>
     */
    public static void pUsername(Configuration configuration) {
        PUsername p = new PUsername();

        p.execute(configuration);
    }
}
